### ISSUE TITLE
[1.8.1] NullPointerException - Kicking in PvP

### ISSUE THREAD

**Issue by OhBlihv** [np98765/BattleKits#17] opened 2012-12-07 23:54 UTC
CraftBukkit version: Spigot #298 (Or builds before Bukkit changed API calls)
Plugin list: 
Plugins (39): WorldBorder, Ptweaks, WorldEdit, AutoSoup, SimpleSignEdit, Vault, PlayerHeads, AntiRelog, PermissionsEx, LogBlock, WorldGuard, PvPTimer, HomeSpawnPlus, mChatSuite, EndReset, MineCoupon, iConomy, ReportRTS, pvparena, MasterPromote, MobSpawnControl, MSocial, Votifier, MobArena, mcMMO, AutoAnnouncer, Essentials, Factions, BattleKits, XrayInformer, ServerSigns, VanishNoPacket, MAdvanced, ecoCreature, AutoRank, CompatNoCheatPlus, ChestShop, NoCheatPlus, MCBans

BattleKits version: 1.8.1 (#1585)
Config file link (pastebin.com): 
http://pastebin.com/ArFa0Jtn
http://pastebin.com/T4TnnLbu
Server log link (pastebin.com):

When does the error occur?
Possibly in or after combat.

Steps to reproduce error:
Continued playing/combat.
(It does seem related to PvPing)

Any other relevant info:
[WARNING] Failed to handle packet for dagraygray/127.0.0.1: java.lang.NullPointerException
java.lang.NullPointerException

(Irrelevant but annoying)
[INFO] [33;22m[AntiRelog] [32;1mdagraygray has logged off during combat.[m
[INFO] [32;1mCowards will not be tolerated on this server.[m

**Comment by lol768** [comment] 2012-12-08 12:33
Thanks for the informative report. Is there any info on where the actual NPE is occurring (like files, line references). Can you ensure that the issue goes away when the plugin is removed?

It doesn't look like a BattleKits issue (unsure why it would kick a player) but I'll look into it.

**Comment by lol768** [comment] 2012-12-08 17:23
Does this issue persist in 1.8.3? Can I have the full stack trace?

**Comment by np98765** [comment] 2012-12-09 16:16
Also, for the last part, that's not a BattleKits issue.  I'm not entirely sure what plugin causes it, but I've had that in my server log for longer than BattleKits has existed.

**Comment by lol768** [comment] 2012-12-09 20:31
Yeah, gonna close this as I can't reproduce it on my server. If you can remove all plugins and then add BattleKits (with the latest CraftBukkit dev build + latest BattleKits v1.8.4) then please reopen the issue.

**Closed as completed by lol768** 2012-12-09 20:31 UTC
Labels: invalid
